"""One toolbar and an image canvas."""

from PySide6.QtCore import Qt, QPoint
from PySide6.QtWidgets import (
    QWidget,
    QFrame,
    QVBoxLayout,
    QHBoxLayout,
    QLabel,
    QAbstractSpinBox,
    QMenu,
    QDialog,
    QFormLayout,
    QSpinBox,
    QDoubleSpinBox,
    QCheckBox,
    QProgressBar,
    QComboBox,
    QSizePolicy,
)
from .theme import ElideLabel
from .widgets import MButton
from ..core import region_contains


def build_ui(w, Canvas):
    root = QWidget()
    w.setCentralWidget(root)
    layout = QVBoxLayout(root)
    layout.setContentsMargins(16, 12, 16, 8)
    layout.setSpacing(10)
    bar = QHBoxLayout()
    bar.setSpacing(4)

    def button(text, action, tip, icon=None, role="tonal"):
        b = MButton(text, icon, role, height=44, tip=tip)
        b.setToolTip(tip)
        b.clicked.connect(action)
        bar.addWidget(b)
        return b

    w.open_btn = button("開く", w.open_dialog, "PNGを追加（複数選択可）", "folder")
    bar.addSpacing(8)
    w.detect_btn = button("自動検出", w.detect, "男性器・女性器の候補を検出", "auto", "primary")
    w.draw_btn = MButton("範囲追加", "add", height=44)
    w.draw_btn.setCheckable(True)
    w.draw_btn.setToolTip("対象を大まかに囲むと輪郭を自動抽出")
    w.draw_btn.toggled.connect(lambda checked: w.set_mode("draw" if checked else "select"))
    bar.addWidget(w.draw_btn)
    w.undo_btn = button("", w.undo, "戻す", "undo", "ghost")
    w.mosaic_controls = QWidget()
    adjustments = QHBoxLayout(w.mosaic_controls)
    adjustments.setContentsMargins(8, 0, 8, 0)
    adjustments.setSpacing(6)
    adjustments.addWidget(QLabel("粗さ"))
    w.block = QSpinBox()
    w.block.setRange(4, 1000)
    w.block.setSuffix(" px")
    w.block.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
    w.block.setFixedSize(88, 40)
    w.block.setAlignment(Qt.AlignmentFlag.AlignCenter)
    w.block.setAccessibleName("モザイクの粗さ")
    w.block.valueChanged.connect(w.mosaic_changed)
    adjustments.addWidget(w.block)
    adjustments.addSpacing(6)
    adjustments.addWidget(QLabel("余白"))
    w.margin = QSpinBox()
    w.margin.setRange(0, 100)
    w.margin.setValue(15)
    w.margin.setSuffix(" %")
    w.margin.setFixedSize(76, 40)
    w.margin.setAlignment(Qt.AlignmentFlag.AlignCenter)
    w.margin.setAccessibleName("モザイク範囲の余白")
    w.margin.setToolTip("輪郭から外側に広げる範囲。現在の画像に適用します。")
    w.margin.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
    w.margin.valueChanged.connect(w.mosaic_changed)
    adjustments.addWidget(w.margin)
    bar.addWidget(w.mosaic_controls)
    bar.addStretch()
    w.save_btn = button("保存", w.export, "処理済み画像を保存")
    w.more_btn = MButton("", "more", "ghost", height=44, tip="その他の操作")
    w.more_btn.setAccessibleName("その他の操作")
    bar.addWidget(w.more_btn)
    w.toolbar_layout = bar
    w.toolbar_group = QVBoxLayout()
    w.toolbar_group.setSpacing(6)
    w.toolbar_group.addLayout(bar)
    w.compact_toolbar = False
    layout.addLayout(w.toolbar_group)

    w.canvas = Canvas()
    w.canvas.edited.connect(w.canvas_edited)
    w.canvas.selection.connect(w.selection_changed)
    w.canvas.filesDropped.connect(w.open_paths)
    w.canvas.setContextMenuPolicy(Qt.ContextMenuPolicy.CustomContextMenu)
    w.canvas.customContextMenuRequested.connect(lambda pos: canvas_menu(w, pos))
    w.canvas.setToolTip(
        "輪郭の点をドラッグで調整・内側をドラッグで移動。右クリックで描き直し・削除。\nホイールで拡大縮小、Shift＋ドラッグで表示位置を移動。"
    )
    stage = QFrame()
    stage.setObjectName("stage")
    stage_layout = QVBoxLayout(stage)
    stage_layout.setContentsMargins(12, 12, 12, 12)
    stage_layout.addWidget(w.canvas)
    layout.addWidget(stage, 1)
    w.batch_bar = QWidget()
    batch = QHBoxLayout(w.batch_bar)
    batch.setContentsMargins(0, 0, 0, 0)
    batch.setSpacing(4)
    w.batch_detect_btn = MButton("一括処理", "auto", "primary", height=40)
    w.batch_detect_btn.clicked.connect(w.start_batch)
    batch.addWidget(w.batch_detect_btn)
    w.image_picker = QComboBox()
    w.image_picker.setAccessibleName("確認する画像")
    w.image_picker.setMinimumWidth(60)
    w.image_picker.setSizePolicy(QSizePolicy.Policy.Ignored, QSizePolicy.Policy.Fixed)
    w.image_picker.setFixedHeight(38)
    w.image_picker.currentIndexChanged.connect(w.switch_document)
    batch.addWidget(w.image_picker, 1)
    w.previous_btn = MButton("", "previous", "ghost", height=40, tip="前の画像")
    w.previous_btn.clicked.connect(lambda: w.step_document(-1))
    batch.addWidget(w.previous_btn)
    w.next_btn = MButton("", "next", "ghost", height=40, tip="次の画像")
    w.next_btn.clicked.connect(lambda: w.step_document(1))
    batch.addWidget(w.next_btn)
    w.review_btn = MButton("確認して次へ", "check", height=40)
    w.review_btn.clicked.connect(w.mark_reviewed)
    batch.addWidget(w.review_btn)
    w.batch_export_btn = MButton("まとめて保存", height=40)
    w.batch_export_btn.setToolTip("確認済みの画像だけをPNGで保存")
    w.batch_export_btn.clicked.connect(lambda: w.export_reviewed())
    batch.addWidget(w.batch_export_btn)
    layout.addWidget(w.batch_bar)
    w.batch_bar.hide()
    w.progress = QProgressBar()
    w.progress.setRange(0, 0)
    w.progress.setTextVisible(False)
    w.progress.setFixedHeight(3)
    w.progress.hide()
    layout.addWidget(w.progress)
    bottom = QHBoxLayout()
    w.status = ElideLabel("")
    bottom.addWidget(w.status, 1)
    w.zoom_label = QLabel("")
    w.zoom_label.setObjectName("secondaryText")
    w.canvas.zoomed.connect(lambda n: w.zoom_label.setText(f"{n}%"))
    bottom.addWidget(w.zoom_label)
    layout.addLayout(bottom)

    w.detection_dialog = QDialog(w)
    w.detection_dialog.setWindowTitle("検出オプション")
    w.detection_dialog.setWindowModality(Qt.WindowModality.WindowModal)
    w.detection_dialog.setMinimumWidth(340)
    form = QFormLayout(w.detection_dialog)
    form.setContentsMargins(24, 24, 24, 24)
    form.setSpacing(16)
    w.threshold = QDoubleSpinBox()
    w.threshold.setRange(0.05, 0.95)
    w.threshold.setSingleStep(0.05)
    w.threshold.setValue(w.preferences.value("detection/threshold", 0.30, type=float))
    w.threshold.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
    w.threshold.setToolTip("低くすると候補が増えます。変更後に再検出してください。")
    form.addRow("検出しきい値", w.threshold)
    w.tiled = QCheckBox("分割して細部も検出")
    w.tiled.setChecked(w.preferences.value("detection/tiled", True, type=bool))
    form.addRow(w.tiled)
    hint = QLabel("現在の画像と、これから追加する画像の検出に適用します。")
    hint.setWordWrap(True)
    hint.setObjectName("secondaryText")
    form.addRow(hint)
    w.threshold.valueChanged.connect(w.detection_options_changed)
    w.tiled.toggled.connect(w.detection_options_changed)
    done = MButton("閉じる", role="primary", height=44)
    done.clicked.connect(w.detection_dialog.accept)
    done_row = QHBoxLayout()
    done_row.addStretch()
    done_row.addWidget(done)
    form.addRow(done_row)

    w.more_menu = QMenu(w)
    w.dark_action = w.more_menu.addAction("ダークモード")
    w.dark_action.setCheckable(True)
    w.dark_action.toggled.connect(w.set_dark_mode)
    w.more_menu.addSeparator()
    w.detection_options_action = w.more_menu.addAction("検出オプション…", w.detection_dialog.open)
    w.more_menu.addSeparator()
    w.outline = w.more_menu.addAction("枠を表示")
    w.outline.setCheckable(True)
    w.outline.setChecked(True)
    w.outline.toggled.connect(w.toggle_outlines)
    w.original = w.more_menu.addAction("元画像を表示")
    w.original.setCheckable(True)
    w.original.toggled.connect(w.show_original)
    w.more_menu.addAction("全体表示", w.canvas.fit_image)
    w.more_menu.addAction("等倍表示", w.canvas.actual_size)
    w.more_menu.addSeparator()
    w.lasso_action = w.more_menu.addAction("手描きで囲む", w.start_lasso)
    w.redraw_action = w.more_menu.addAction("輪郭を描き直す", lambda: w.start_lasso(replace=True))
    w.refine_action = w.more_menu.addAction("輪郭を再推定", lambda: w.refine_selected())
    w.more_menu.addSeparator()
    w.delete_btn = w.more_menu.addAction("選択範囲を削除", w.remove_selected)
    w.redo_btn = w.more_menu.addAction("やり直す", w.redo)
    w.more_menu.addSeparator()
    w.project_save_btn = w.more_menu.addAction("作業を保存…", w.save_work)
    w.project_open_btn = w.more_menu.addAction("作業を開く…", w.open_work)
    w.remove_image_action = w.more_menu.addAction("現在の画像を一覧から外す", w.remove_current_image)
    w.more_btn.clicked.connect(lambda: w.more_menu.popup(w.more_btn.mapToGlobal(QPoint(0, w.more_btn.height() + 6))))


def canvas_menu(w, pos):
    point = w.canvas.mapToScene(pos)
    hit = next((r for r in reversed(w.regions) if region_contains(r, point.x(), point.y())), None)
    if hit:
        w.canvas.select(hit.uid)
    menu = QMenu(w)
    menu.addAction(w.redraw_action)
    menu.addAction(w.refine_action)
    menu.addSeparator()
    menu.addAction(w.delete_btn)
    menu.addAction(w.redo_btn)
    menu.exec(w.canvas.viewport().mapToGlobal(pos))
